### ISSUE TITLE
Temperature data missing

### ISSUE THREAD

**Issue by Olivier6767** [ssenart/lovelace-gazpar-card#34]
I'm using this lovelace integration along with the gazpar integration version 1.3.5.
I'm getting the values and they display nicely, except that I don't have any temperature data in the weekly graph.
Is this temperature supposed to be retrieved from the GRDF site by the gazpar integration?
Is there anything I should setup or check?

Thanks!

**Comment by ssenart** [comment]
Hello, the temperature is retrieved and displayed only for daily graph.

Yes, the temperature is coming from GRDF.

**Comment by Olivier6767** [comment]
Thanks for the information.
Is there a sensor created for in HA that I can check?
What is the name?
Do I need to set anything up for the temperature to work?

When connecting to my GRDF account I can see the temperature graph.

**Comment by ssenart** [comment]
The corresponding default entity name is sensor.gazpar.

Its attributes give the data values per period. For example:

```yaml
daily: 
- time_period: 20/09/2024
  start_index_m3: 19338
  end_index_m3: 19340
  volume_m3: 1.8
  energy_kwh: 20
  converter_factor_kwh/m3: 11.26827
  temperature_degC: 18.55
  type: Mesuré
  timestamp: '2024-09-22T13:02:58.726288'
```
  
  temperature_degC is the temperature.
